const PLATFORMS = [
  { id:'instagram', name:'Instagram', badge:'IG', color:'linear-gradient(135deg,#7b35c8,#ef3d73 58%,#f59a3b)', login:'https://www.instagram.com/accounts/login/', sessionUrl:'https://www.instagram.com/', description:'Open Instagram and choose Create', composer:()=>'https://www.instagram.com/' },
  { id:'tiktok', name:'TikTok', badge:'TT', color:'#141918', login:'https://www.tiktok.com/login', sessionUrl:'https://www.tiktok.com/upload', description:'Open the official upload page', composer:()=>'https://www.tiktok.com/upload' },
  { id:'facebook', name:'Facebook', badge:'f', color:'#1877f2', login:'https://www.facebook.com/login', sessionUrl:'https://www.facebook.com/', description:'Share a link or create a post', composer:p=>p.link?`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(p.link)}&quote=${encodeURIComponent(buildCaption(p))}`:'https://www.facebook.com/' },
  { id:'x', name:'X', badge:'X', color:'#111111', login:'https://x.com/i/flow/login', sessionUrl:'https://x.com/home', description:'Caption and link can be prefilled', composer:p=>`https://twitter.com/intent/tweet?text=${encodeURIComponent([buildCaption(p),p.link].filter(Boolean).join('\n\n'))}` },
  { id:'linkedin', name:'LinkedIn', badge:'in', color:'#0a66c2', login:'https://www.linkedin.com/login', sessionUrl:'https://www.linkedin.com/feed/', description:'Share a link or create an update', composer:p=>p.link?`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(p.link)}`:'https://www.linkedin.com/feed/' },
  { id:'youtube', name:'YouTube', badge:'YT', color:'#ff0033', login:'https://accounts.google.com/ServiceLogin?service=youtube&continue=https%3A%2F%2Fwww.youtube.com%2F', sessionUrl:'https://www.youtube.com/upload', description:'Open YouTube Studio upload', composer:()=>'https://www.youtube.com/upload' }
];
const STATUSES={draft:'Draft',approval:'Awaiting approval',scheduled:'Scheduled',ready:'Ready to publish',published:'Published'};
const COLOURS=['#ef111b','#356fd5','#18a56e','#d99a12','#8a54cf','#e56625'];
const DEFAULT_POST_URL='https://www.techfixlab.co.uk';
const APP_VERSION='2.0';
const VERSION_HISTORY=[
  {version:'2.0',date:'14 August 2026',summary:'Major team collaboration and application-management release.',changes:['Added user profile settings','Added secure password changes','Added version checker and dedicated changelog tab','Added shared information-request workflow','Added content-approval requests','Added manual social inbox conversations','Added internal team notes and reply records','Added private optimised media library','Added persistent browser social-session workflow','Made login resilient when optional feature migrations are pending']},
  {version:'1.5',date:'14 August 2026',summary:'Publishing workflow and personalisation update.',changes:['Personalised dashboard greeting','Fixed Tech Fix Lab website link','White sidebar redesign','Browser session readiness','Publishing-calendar improvements']},
  {version:'1.0',date:'14 August 2026',summary:'Initial Tech Social CRM release.',changes:['Secure Supabase login','Shared post calendar','Campaigns and publishing queue','Official social posting launchers']}
];
const BROWSER_SESSION_KEY='tech-social-browser-sessions-v1';
const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const el={
  sidebar:$('#sidebar'),scrim:$('#sidebarScrim'),mobileMenu:$('#mobileMenuButton'),pageKicker:$('#pageKicker'),pageTitle:$('#pageTitle'),globalSearch:$('#globalSearch'),
  todayLabel:$('#todayLabel'),greetingLabel:$('#greetingLabel'),workspaceStatusText:$('#workspaceStatusText'),heroNextTitle:$('#heroNextTitle'),heroNextTime:$('#heroNextTime'),
  totalPostsStat:$('#totalPostsStat'),duePostsStat:$('#duePostsStat'),scheduledPostsStat:$('#scheduledPostsStat'),publishedPostsStat:$('#publishedPostsStat'),upcomingList:$('#upcomingList'),miniAccounts:$('#miniAccounts'),recentPostsBody:$('#recentPostsBody'),
  calendarNavCount:$('#calendarNavCount'),postsNavCount:$('#postsNavCount'),mediaNavCount:$('#mediaNavCount'),inboxNavCount:$('#inboxNavCount'),requestsNavCount:$('#requestsNavCount'),queueNavCount:$('#queueNavCount'),accountsNavCount:$('#accountsNavCount'),calendarMonthTitle:$('#calendarMonthTitle'),calendarGrid:$('#calendarGrid'),previousMonthButton:$('#previousMonthButton'),nextMonthButton:$('#nextMonthButton'),todayButton:$('#todayButton'),
  postSearch:$('#postSearch'),statusFilter:$('#statusFilter'),platformFilter:$('#platformFilter'),clearFiltersButton:$('#clearFiltersButton'),allPostsBody:$('#allPostsBody'),postsEmpty:$('#postsEmpty'),mediaCountStat:$('#mediaCountStat'),mediaStorageStat:$('#mediaStorageStat'),mediaSavedStat:$('#mediaSavedStat'),mediaSearch:$('#mediaSearch'),mediaTypeFilter:$('#mediaTypeFilter'),mediaGrid:$('#mediaGrid'),mediaEmpty:$('#mediaEmpty'),campaignGrid:$('#campaignGrid'),newCampaignButton:$('#newCampaignButton'),queueList:$('#queueList'),queueEmpty:$('#queueEmpty'),accountsGrid:$('#accountsGrid'),openRequestsStat:$('#openRequestsStat'),progressRequestsStat:$('#progressRequestsStat'),completedRequestsStat:$('#completedRequestsStat'),requestStatusFilter:$('#requestStatusFilter'),requestTypeFilter:$('#requestTypeFilter'),requestList:$('#requestList'),requestsEmpty:$('#requestsEmpty'),newRequestButton:$('#newRequestButton'),threadSearch:$('#threadSearch'),threadList:$('#threadList'),threadEmpty:$('#threadEmpty'),conversationPlaceholder:$('#conversationPlaceholder'),activeConversation:$('#activeConversation'),conversationPlatformBadge:$('#conversationPlatformBadge'),conversationContact:$('#conversationContact'),conversationSubject:$('#conversationSubject'),conversationStatus:$('#conversationStatus'),messageList:$('#messageList'),messageForm:$('#messageForm'),messageType:$('#messageType'),messageBody:$('#messageBody'),newThreadButton:$('#newThreadButton'),
  postModal:$('#postModal'),postModalTitle:$('#postModalTitle'),postForm:$('#postForm'),postId:$('#postId'),postCaption:$('#postCaption'),postCaptionCount:$('#postCaptionCount'),postLink:$('#postLink'),postHashtags:$('#postHashtags'),postNotes:$('#postNotes'),platformPicker:$('#platformPicker'),postDate:$('#postDate'),postTime:$('#postTime'),postCampaign:$('#postCampaign'),postStatus:$('#postStatus'),postMediaSelect:$('#postMediaSelect'),selectedMediaInfo:$('#selectedMediaInfo'),openMediaUploadButton:$('#openMediaUploadButton'),postFormError:$('#postFormError'),deletePostButton:$('#deletePostButton'),
  mediaUploadModal:$('#mediaUploadModal'),mediaDropZone:$('#mediaDropZone'),mediaUploadInput:$('#mediaUploadInput'),mediaUploadQueue:$('#mediaUploadQueue'),mediaUploadError:$('#mediaUploadError'),startMediaUploadButton:$('#startMediaUploadButton'),
  requestModal:$('#requestModal'),requestForm:$('#requestForm'),requestId:$('#requestId'),requestType:$('#requestType'),requestPriority:$('#requestPriority'),requestTitle:$('#requestTitle'),requestDetails:$('#requestDetails'),requestAssignee:$('#requestAssignee'),requestRelatedPost:$('#requestRelatedPost'),deleteRequestButton:$('#deleteRequestButton'),threadModal:$('#threadModal'),threadForm:$('#threadForm'),threadPlatform:$('#threadPlatform'),threadContactName:$('#threadContactName'),threadContactHandle:$('#threadContactHandle'),threadSubject:$('#threadSubject'),threadFirstMessage:$('#threadFirstMessage'),
  campaignModal:$('#campaignModal'),campaignForm:$('#campaignForm'),campaignId:$('#campaignId'),campaignName:$('#campaignName'),campaignDescription:$('#campaignDescription'),colourPicker:$('#colourPicker'),deleteCampaignButton:$('#deleteCampaignButton'),
  publishModal:$('#publishModal'),publishModalTitle:$('#publishModalTitle'),publishCaptionPreview:$('#publishCaptionPreview'),publishMediaReference:$('#publishMediaReference'),publishMediaName:$('#publishMediaName'),openPublishMediaButton:$('#openPublishMediaButton'),publishResults:$('#publishResults'),openAllButton:$('#openAllButton'),copyOnlyButton:$('#copyOnlyButton'),markPublishedButton:$('#markPublishedButton'),
  profileForm:$('#profileForm'),profileAvatar:$('#profileAvatar'),profileDisplayName:$('#profileDisplayName'),profileEmail:$('#profileEmail'),profileMessage:$('#profileMessage'),passwordForm:$('#passwordForm'),newPassword:$('#newPassword'),confirmPassword:$('#confirmPassword'),passwordMessage:$('#passwordMessage'),versionStatus:$('#versionStatus'),versionHistory:$('#versionHistory'),checkVersionButton:$('#checkVersionButton'),exportButton:$('#exportButton'),importButton:$('#importButton'),importInput:$('#importInput'),toastRegion:$('#toastRegion'),
  authGate:$('#authGate'),loginPanel:$('#loginPanel'),setupPanel:$('#setupPanel'),cloudLoading:$('#cloudLoading'),authForm:$('#authForm'),authEmail:$('#authEmail'),authPassword:$('#authPassword'),authTitle:$('#authTitle'),authSubtitle:$('#authSubtitle'),authSubmitButton:$('#authSubmitButton'),authMessage:$('#authMessage'),authTabs:$('#authTabs'),forgotPasswordButton:$('#forgotPasswordButton'),recheckConfigButton:$('#recheckConfigButton'),userMenuButton:$('#userMenuButton'),userDropdown:$('#userDropdown'),logoutButton:$('#logoutButton'),userInitials:$('#userInitials'),userDisplayName:$('#userDisplayName'),userEmailLabel:$('#userEmailLabel'),dropdownEmail:$('#dropdownEmail')
};

let state={posts:[],campaigns:[],media:[],requests:[],threads:[],messages:[],accounts:Object.fromEntries(PLATFORMS.map(p=>[p.id,false]))};
let browserSessions=loadBrowserSessions();
let db=null;
let currentUser=null;
let currentDisplayName='';
let realtimeChannel=null;
let realtimeTimer=null;
let schemaWarnings=[];
let appInitialized=false;
let authMode='signin';
let activeView='dashboard';
let calendarCursor=new Date();calendarCursor.setDate(1);
let selectedPlatforms=[];
let selectedCampaignColour=COLOURS[0];
let publishingPostId=null;
let activeThreadId='';
let selectedMediaId='';
let queuedMediaFiles=[];
const mediaSignedUrls=new Map();

function loadBrowserSessions(){try{return{...Object.fromEntries(PLATFORMS.map(p=>[p.id,false])),...JSON.parse(localStorage.getItem(BROWSER_SESSION_KEY)||'{}')}}catch{return Object.fromEntries(PLATFORMS.map(p=>[p.id,false]))}}
function saveBrowserSessions(){localStorage.setItem(BROWSER_SESSION_KEY,JSON.stringify(browserSessions))}
function uid(prefix='id'){return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`}
function toLocalDate(date){const d=new Date(date.getTime()-date.getTimezoneOffset()*60000);return d.toISOString().slice(0,10)}
function postFromDb(row){return{id:row.id,caption:row.caption||'',link:DEFAULT_POST_URL,hashtags:row.hashtags||'',notes:row.notes||'',platforms:row.platforms||[],scheduledAt:row.scheduled_at,status:row.status,campaignId:row.campaign_id||'',mediaId:row.media_id||'',mediaName:row.media_name||'',createdAt:row.created_at,updatedAt:row.updated_at}}
function postToDb(post){return{id:post.id,caption:post.caption,link:DEFAULT_POST_URL,hashtags:post.hashtags||'',notes:post.notes||'',platforms:post.platforms||[],scheduled_at:post.scheduledAt,status:post.status,campaign_id:post.campaignId||null,media_id:post.mediaId||null,media_name:post.mediaName||'',created_at:post.createdAt,updated_at:post.updatedAt,updated_by:currentUser?.id||null}}
function campaignFromDb(row){return{id:row.id,name:row.name,description:row.description||'',colour:row.colour||'#ef111b',createdAt:row.created_at,updatedAt:row.updated_at}}
function campaignToDb(item){return{id:item.id,name:item.name,description:item.description||'',colour:item.colour||'#ef111b',created_at:item.createdAt,updated_at:item.updatedAt||new Date().toISOString()}}
function mediaFromDb(row){return{id:row.id,path:row.storage_path,hash:row.content_hash,name:row.original_name,mime:row.mime_type,type:row.media_type,size:Number(row.size_bytes||0),originalSize:Number(row.original_size_bytes||row.size_bytes||0),width:row.width,height:row.height,duration:Number(row.duration_seconds||0),createdAt:row.created_at}}
function requestFromDb(row){return{id:row.id,type:row.request_type,title:row.title,details:row.details||'',priority:row.priority,status:row.status,requestedBy:row.requested_by,requestedByEmail:row.requested_by_email,requestedByName:row.requested_by_name,assignedTo:row.assigned_to_email||'',relatedPostId:row.related_post_id||'',relatedCampaignId:row.related_campaign_id||'',createdAt:row.created_at,updatedAt:row.updated_at}}
function threadFromDb(row){return{id:row.id,platform:row.platform,contactName:row.contact_name,contactHandle:row.contact_handle||'',subject:row.subject||'',status:row.status,createdBy:row.created_by,createdAt:row.created_at,updatedAt:row.updated_at,lastMessageAt:row.last_message_at}}
function messageFromDb(row){return{id:row.id,threadId:row.thread_id,type:row.message_type,body:row.body,senderName:row.sender_name,senderUserId:row.sender_user_id,createdAt:row.created_at}}
function formatBytes(bytes=0){if(bytes<1024)return`${bytes} B`;if(bytes<1048576)return`${(bytes/1024).toFixed(1)} KB`;if(bytes<1073741824)return`${(bytes/1048576).toFixed(1)} MB`;return`${(bytes/1073741824).toFixed(1)} GB`}
function configReady(){const c=window.TECH_SOCIAL_CONFIG||{};return /^https:\/\/.+\.supabase\.co$/.test(c.supabaseUrl||'')&&(c.supabaseAnonKey||'').length>40&&!String(c.supabaseAnonKey).includes('PASTE_')}
function setAuthMessage(message='',success=false){el.authMessage.textContent=message;el.authMessage.classList.toggle('success',success)}
function setAuthMode(mode){authMode=mode;$$('[data-auth-mode]').forEach(b=>b.classList.toggle('active',b.dataset.authMode===mode));const signup=mode==='signup',recovery=mode==='recovery';el.authTitle.textContent=recovery?'Choose a new password':signup?'Create your account':'Welcome back';el.authSubtitle.textContent=recovery?'Enter a new password with at least eight characters.':signup?'Use an email already approved by your administrator.':'Sign in with your approved team email.';el.authSubmitButton.textContent=recovery?'Save new password':signup?'Create secure account':'Sign in securely';el.forgotPasswordButton.hidden=signup||recovery;el.authTabs.hidden=recovery;el.authEmail.closest('label').hidden=recovery;el.authPassword.autocomplete=signup||recovery?'new-password':'current-password';setAuthMessage()}
async function loadCloudData(){
  const [postsResult,campaignsResult,accountsResult,mediaResult,requestsResult,threadsResult,messagesResult]=await Promise.all([db.from('posts').select('*').order('scheduled_at'),db.from('campaigns').select('*').order('created_at'),db.from('social_accounts').select('*'),db.from('media_assets').select('*').order('created_at'),db.from('team_requests').select('*').order('updated_at',{ascending:false}),db.from('social_threads').select('*').order('last_message_at',{ascending:false}),db.from('social_messages').select('*').order('created_at')]);
  const coreError=postsResult.error||campaignsResult.error||accountsResult.error;if(coreError)throw coreError;schemaWarnings=[];if(mediaResult.error)schemaWarnings.push('media library');if(requestsResult.error)schemaWarnings.push('team requests');if(threadsResult.error||messagesResult.error)schemaWarnings.push('social inbox');
  state.posts=(postsResult.data||[]).map(postFromDb);state.campaigns=(campaignsResult.data||[]).map(campaignFromDb);state.media=mediaResult.error?[]:(mediaResult.data||[]).map(mediaFromDb);state.requests=requestsResult.error?[]:(requestsResult.data||[]).map(requestFromDb);state.threads=threadsResult.error?[]:(threadsResult.data||[]).map(threadFromDb);state.messages=messagesResult.error?[]:(messagesResult.data||[]).map(messageFromDb);state.accounts=Object.fromEntries(PLATFORMS.map(p=>[p.id,false]));(accountsResult.data||[]).forEach(row=>state.accounts[row.platform]=Boolean(row.ready));
}
async function verifyAndOpenWorkspace(user){
  if(!user||(currentUser?.id===user.id&&el.authGate.hidden))return;
  el.cloudLoading.hidden=false;el.authGate.hidden=true;
  try{
    const{data:allowed,error}=await db.rpc('is_allowed_user');if(error)throw error;
    if(!allowed){await db.auth.signOut();throw new Error('This email is not on the approved Tech Social team list. Ask the administrator to add it in Supabase.')}
    currentUser=user;const profileResult=await db.from('allowed_users').select('display_name');await loadCloudData();
    const email=user.email||'Team member',profileName=profileResult.data?.[0]?.display_name?.trim(),name=profileName||user.user_metadata?.display_name||email.split('@')[0].replace(/[._-]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase()),initials=name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();currentDisplayName=name;el.userDisplayName.textContent=name;el.userEmailLabel.textContent=email;el.dropdownEmail.textContent=email;el.userInitials.textContent=initials||'TL';el.profileDisplayName.value=name;el.profileEmail.value=email;el.profileAvatar.textContent=initials||'TL';
    if(!appInitialized){renderPlatformPicker();renderColourPicker();bindEvents();el.postDate.min=toLocalDate(new Date());appInitialized=true;if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{})}
    setDateGreeting();renderAll();showView('dashboard',false);subscribeRealtime();el.cloudLoading.hidden=true;el.authGate.hidden=true;if(schemaWarnings.length)setTimeout(()=>toast(`Database migration required for: ${schemaWarnings.join(', ')}. Core CRM access is still available.`,true),300);
  }catch(error){currentUser=null;el.cloudLoading.hidden=true;el.authGate.hidden=false;el.setupPanel.hidden=true;el.loginPanel.hidden=false;setAuthMode('signin');setAuthMessage(error.message||'Could not open the shared workspace.')}
}
function subscribeRealtime(){if(realtimeChannel)db.removeChannel(realtimeChannel);realtimeChannel=db.channel('tech-social-team').on('postgres_changes',{event:'*',schema:'public',table:'posts'},scheduleCloudRefresh).on('postgres_changes',{event:'*',schema:'public',table:'campaigns'},scheduleCloudRefresh).on('postgres_changes',{event:'*',schema:'public',table:'social_accounts'},scheduleCloudRefresh).on('postgres_changes',{event:'*',schema:'public',table:'media_assets'},scheduleCloudRefresh).on('postgres_changes',{event:'*',schema:'public',table:'team_requests'},scheduleCloudRefresh).on('postgres_changes',{event:'*',schema:'public',table:'social_threads'},scheduleCloudRefresh).on('postgres_changes',{event:'*',schema:'public',table:'social_messages'},scheduleCloudRefresh).subscribe()}
function scheduleCloudRefresh(){clearTimeout(realtimeTimer);realtimeTimer=setTimeout(async()=>{if(!currentUser)return;try{await loadCloudData();renderAll()}catch{}},250)}
async function initializeAuth(){
  bindAuthEvents();
  if(!configReady()){el.loginPanel.hidden=true;el.setupPanel.hidden=false;el.authGate.hidden=false;return}
  try{
    db=window.supabase.createClient(window.TECH_SOCIAL_CONFIG.supabaseUrl,window.TECH_SOCIAL_CONFIG.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
    db.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'){setAuthMode('recovery');el.authGate.hidden=false;el.loginPanel.hidden=false;el.setupPanel.hidden=true;el.cloudLoading.hidden=true}else if(event==='SIGNED_OUT'){currentUser=null;currentDisplayName='';el.authGate.hidden=false;el.loginPanel.hidden=false;el.setupPanel.hidden=true;el.userDropdown.hidden=true}else if(event==='SIGNED_IN'&&session?.user){setTimeout(()=>verifyAndOpenWorkspace(session.user),0)}});
    const{data:{session}}=await db.auth.getSession();if(session?.user)await verifyAndOpenWorkspace(session.user);else{el.authGate.hidden=false;el.loginPanel.hidden=false;el.setupPanel.hidden=true}
  }catch(error){el.loginPanel.hidden=false;el.setupPanel.hidden=true;setAuthMessage(`Supabase connection failed: ${error.message}`)}
}
function bindAuthEvents(){
  $$('[data-auth-mode]').forEach(button=>button.addEventListener('click',()=>setAuthMode(button.dataset.authMode)));
  el.authForm.addEventListener('submit',handleAuthSubmit);el.forgotPasswordButton.addEventListener('click',handleForgotPassword);el.recheckConfigButton.addEventListener('click',()=>location.reload());
  el.userMenuButton.addEventListener('click',event=>{event.stopPropagation();el.userDropdown.hidden=!el.userDropdown.hidden});el.logoutButton.addEventListener('click',async()=>{el.userDropdown.hidden=true;await db.auth.signOut();state={posts:[],campaigns:[],media:[],requests:[],threads:[],messages:[],accounts:{}}});document.addEventListener('click',event=>{if(!event.target.closest('.user-menu-wrap'))el.userDropdown.hidden=true});
}
async function handleAuthSubmit(event){event.preventDefault();if(!db)return;const email=el.authEmail.value.trim().toLowerCase(),password=el.authPassword.value;setAuthMessage();el.authSubmitButton.disabled=true;el.authSubmitButton.textContent='Please wait…';try{
  if(authMode==='recovery'){const{error}=await db.auth.updateUser({password});if(error)throw error;setAuthMessage('Password updated. Opening your workspace…',true);const{data:{user}}=await db.auth.getUser();await verifyAndOpenWorkspace(user);return}
  if(authMode==='signup'){const{data,error}=await db.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}});if(error)throw error;if(data.session)await verifyAndOpenWorkspace(data.user);else setAuthMessage('Check your email and confirm the account, then return here to sign in.',true)}
  else{const{data,error}=await db.auth.signInWithPassword({email,password});if(error)throw error;await verifyAndOpenWorkspace(data.user)}
 }catch(error){setAuthMessage(error.message||'Authentication failed.')}finally{el.authSubmitButton.disabled=false;el.authSubmitButton.textContent=authMode==='recovery'?'Save new password':authMode==='signup'?'Create secure account':'Sign in securely'}
}
async function handleForgotPassword(){if(!db)return;const email=el.authEmail.value.trim().toLowerCase();if(!email){setAuthMessage('Enter your approved email address first.');return}const{error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});setAuthMessage(error?error.message:'Password reset email sent. Check your inbox.',!error)}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function normaliseHashtags(value=''){return value.split(/[\s,]+/).map(t=>t.replace(/^#+/,'').replace(/[^\p{L}\p{N}_]/gu,'')).filter(Boolean).map(t=>`#${t}`).join(' ')}
function buildCaption(post){return[post.caption?.trim(),normaliseHashtags(post.hashtags)].filter(Boolean).join('\n\n')}
function formatDateTime(value,short=false){if(!value)return'Unscheduled';const d=new Date(value);return new Intl.DateTimeFormat('en-GB',short?{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}:{weekday:'short',day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(d)}
function formatDayMonth(value){return new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short'}).format(new Date(value))}
function platform(id){return PLATFORMS.find(p=>p.id===id)}
function campaign(id){return state.campaigns.find(c=>c.id===id)}
function postTitle(post){const text=post.caption?.trim()||'Untitled post';return text.length>72?`${text.slice(0,72)}…`:text}
function statusPill(status){return `<span class="status-pill ${status}">${escapeHtml(STATUSES[status]||status)}</span>`}
function platformBadges(ids=[]){return `<div class="platform-stack">${ids.slice(0,4).map(id=>{const p=platform(id);return p?`<span class="network-badge" title="${p.name}" style="background:${p.color}">${p.badge}</span>`:''}).join('')}${ids.length>4?`<span class="network-badge" style="background:#777">+${ids.length-4}</span>`:''}</div>`}
function campaignTag(id){const c=campaign(id);return c?`<span class="campaign-tag"><i style="background:${c.colour}"></i>${escapeHtml(c.name)}</span>`:'<span class="campaign-tag">No campaign</span>'}
function sortedPosts(){return[...state.posts].sort((a,b)=>new Date(a.scheduledAt)-new Date(b.scheduledAt))}
function queuePosts(){return sortedPosts().filter(p=>p.status!=='published'&&p.scheduledAt)}
function isDue(post){return post.scheduledAt&&new Date(post.scheduledAt)<=new Date()&&post.status!=='published'}

function bindEvents(){
  $$('[data-view-link]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();showView(button.dataset.viewLink)}));
  $$('[data-new-post]').forEach(button=>{button.dataset.bound='1';button.addEventListener('click',()=>openPostModal())});
  el.mobileMenu.addEventListener('click',()=>{el.sidebar.classList.toggle('open');el.scrim.classList.toggle('open')});el.scrim.addEventListener('click',closeMenu);
  el.postCaption.addEventListener('input',updateCaptionCount);el.postMediaSelect.addEventListener('change',()=>{selectedMediaId=el.postMediaSelect.value;updateSelectedMediaInfo()});el.openMediaUploadButton.addEventListener('click',openMediaUploadModal);el.postForm.addEventListener('submit',savePostFromForm);el.deletePostButton.addEventListener('click',deleteCurrentPost);
  $$('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>closeModal(el.postModal)));$$('[data-close-media-upload]').forEach(b=>b.addEventListener('click',()=>closeModal(el.mediaUploadModal)));$$('[data-close-request]').forEach(b=>b.addEventListener('click',()=>closeModal(el.requestModal)));$$('[data-close-thread]').forEach(b=>b.addEventListener('click',()=>closeModal(el.threadModal)));$$('[data-upload-media]').forEach(b=>b.addEventListener('click',openMediaUploadModal));$$('[data-close-campaign]').forEach(b=>b.addEventListener('click',()=>closeModal(el.campaignModal)));$$('[data-close-publish]').forEach(b=>b.addEventListener('click',()=>closeModal(el.publishModal)));
  el.previousMonthButton.addEventListener('click',()=>{calendarCursor.setMonth(calendarCursor.getMonth()-1);renderCalendar()});el.nextMonthButton.addEventListener('click',()=>{calendarCursor.setMonth(calendarCursor.getMonth()+1);renderCalendar()});el.todayButton.addEventListener('click',()=>{calendarCursor=new Date();calendarCursor.setDate(1);renderCalendar()});
  [el.postSearch,el.statusFilter,el.platformFilter].forEach(input=>input.addEventListener('input',renderPostsLibrary));[el.mediaSearch,el.mediaTypeFilter].forEach(input=>input.addEventListener('input',renderMediaLibrary));el.mediaUploadInput.addEventListener('change',()=>queueMediaFiles([...el.mediaUploadInput.files]));['dragenter','dragover'].forEach(type=>el.mediaDropZone.addEventListener(type,event=>{event.preventDefault();el.mediaDropZone.classList.add('dragging')}));['dragleave','drop'].forEach(type=>el.mediaDropZone.addEventListener(type,event=>{event.preventDefault();el.mediaDropZone.classList.remove('dragging')}));el.mediaDropZone.addEventListener('drop',event=>queueMediaFiles([...event.dataTransfer.files]));el.startMediaUploadButton.addEventListener('click',uploadQueuedMedia);el.clearFiltersButton.addEventListener('click',()=>{el.postSearch.value='';el.statusFilter.value='all';el.platformFilter.value='all';renderPostsLibrary()});
  el.globalSearch.addEventListener('input',()=>{if(el.globalSearch.value.trim()){el.postSearch.value=el.globalSearch.value;showView('posts');renderPostsLibrary()}});
  el.newCampaignButton.addEventListener('click',()=>openCampaignModal());el.campaignForm.addEventListener('submit',saveCampaignFromForm);el.deleteCampaignButton.addEventListener('click',deleteCurrentCampaign);
  el.openAllButton.addEventListener('click',openPublishingPages);el.openPublishMediaButton.addEventListener('click',openPublishingMedia);el.copyOnlyButton.addEventListener('click',copyPublishingCaption);el.markPublishedButton.addEventListener('click',markPublishingPostComplete);
  el.newRequestButton.addEventListener('click',()=>openRequestModal());el.requestForm.addEventListener('submit',saveRequest);el.deleteRequestButton.addEventListener('click',deleteCurrentRequest);[el.requestStatusFilter,el.requestTypeFilter].forEach(input=>input.addEventListener('change',renderRequests));
  el.newThreadButton.addEventListener('click',openThreadModal);el.threadForm.addEventListener('submit',createThread);el.threadSearch.addEventListener('input',renderInbox);el.messageForm.addEventListener('submit',addThreadMessage);el.conversationStatus.addEventListener('change',updateThreadStatus);
  $$('[data-settings-tab]').forEach(button=>button.addEventListener('click',()=>showSettingsTab(button.dataset.settingsTab)));el.profileForm.addEventListener('submit',saveProfile);el.passwordForm.addEventListener('submit',changePassword);el.checkVersionButton.addEventListener('click',checkForUpdates);
  el.exportButton.addEventListener('click',exportData);el.importButton.addEventListener('click',()=>el.importInput.click());el.importInput.addEventListener('change',importData);
  document.addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();el.globalSearch.focus()}if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='n'){event.preventDefault();openPostModal()}if(event.key==='Escape'){$$('.modal-backdrop:not([hidden])').forEach(closeModal);closeMenu()}});
  $$('.modal-backdrop').forEach(modal=>modal.addEventListener('click',event=>{if(event.target===modal)closeModal(modal)}));
}
function setDateGreeting(){const now=new Date(),firstName=(currentDisplayName||'Tech Lab').trim().split(/\s+/)[0];el.todayLabel.textContent=new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long'}).format(now).toUpperCase();const h=now.getHours();el.greetingLabel.textContent=`${h<12?'Good morning':h<18?'Good afternoon':'Good evening'}, ${firstName}.`}
function showView(view,scroll=true){activeView=view;$$('.view').forEach(v=>v.hidden=v.dataset.view!==view);$$('.nav-item[data-view-link]').forEach(n=>n.classList.toggle('active',n.dataset.viewLink===view));const labels={dashboard:['TECH SOCIAL / OVERVIEW','Content dashboard'],calendar:['TECH SOCIAL / PLANNER','Content calendar'],posts:['TECH SOCIAL / LIBRARY','All social posts'],media:['TECH SOCIAL / MEDIA','Media library'],campaigns:['TECH SOCIAL / CAMPAIGNS','Campaign manager'],inbox:['TECH SOCIAL / INBOX','Social inbox'],requests:['TECH SOCIAL / REQUESTS','Team requests'],settings:['TECH SOCIAL / SETTINGS','Settings'],queue:['TECH SOCIAL / PUBLISHING','Publishing queue'],accounts:['TECH SOCIAL / ACCOUNTS','Social accounts']};[el.pageKicker.textContent,el.pageTitle.textContent]=labels[view]||labels.dashboard;closeMenu();if(view==='calendar')renderCalendar();if(view==='posts')renderPostsLibrary();if(view==='media')renderMediaLibrary();if(view==='campaigns')renderCampaigns();if(view==='inbox')renderInbox();if(view==='requests')renderRequests();if(view==='settings')renderSettings();if(view==='queue')renderQueue();if(view==='accounts')renderAccounts();if(scroll)window.scrollTo({top:0,behavior:'smooth'})}
function closeMenu(){el.sidebar.classList.remove('open');el.scrim.classList.remove('open')}
function renderAll(){renderDashboard();renderCalendar();renderPostsLibrary();renderMediaLibrary();renderCampaigns();renderQueue();renderAccounts();renderRequests();renderInbox();renderSettings();updateCounts()}
function updateCounts(){const queue=queuePosts();const ready=PLATFORMS.filter(p=>browserSessions[p.id]).length;el.postsNavCount.textContent=state.posts.length;el.mediaNavCount.textContent=state.media.length;el.inboxNavCount.textContent=state.threads.filter(thread=>thread.status!=='closed').length;el.requestsNavCount.textContent=state.requests.filter(request=>request.status!=='completed').length;el.calendarNavCount.textContent=state.posts.filter(p=>p.scheduledAt&&p.status!=='published').length;el.queueNavCount.textContent=queue.length;el.accountsNavCount.textContent=ready;el.workspaceStatusText.textContent=`${ready} of ${PLATFORMS.length} ready on this browser`}

function renderDashboard(){
  const now=Date.now(),due=state.posts.filter(p=>p.status!=='published'&&p.scheduledAt&&new Date(p.scheduledAt).getTime()<=now+48*3600000&&new Date(p.scheduledAt).getTime()>=now-24*3600000),scheduled=state.posts.filter(p=>p.status!=='published'&&p.scheduledAt&&new Date(p.scheduledAt)>new Date()),published=state.posts.filter(p=>p.status==='published');
  el.totalPostsStat.textContent=state.posts.length;el.duePostsStat.textContent=due.length;el.scheduledPostsStat.textContent=scheduled.length;el.publishedPostsStat.textContent=published.length;
  const next=sortedPosts().find(p=>p.status!=='published'&&new Date(p.scheduledAt)>=new Date());el.heroNextTitle.textContent=next?postTitle(next):'Nothing scheduled';el.heroNextTime.textContent=next?formatDateTime(next.scheduledAt):'Create a post to start your queue';
  const upcoming=sortedPosts().filter(p=>p.status!=='published'&&new Date(p.scheduledAt)>=new Date()).slice(0,4);el.upcomingList.innerHTML=upcoming.length?upcoming.map(p=>{const d=new Date(p.scheduledAt);return`<article class="upcoming-item" data-edit-post="${p.id}"><div class="date-tile"><small>${d.toLocaleDateString('en-GB',{month:'short'}).toUpperCase()}</small><strong>${d.getDate()}</strong></div><div class="upcoming-copy"><strong>${escapeHtml(postTitle(p))}</strong><small>${d.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})} · ${p.platforms.length} channels</small></div>${statusPill(p.status)}</article>`}).join(''):`<div class="empty-state"><p>No upcoming posts. Create one to begin.</p><button class="button button-primary" data-new-post>Create post</button></div>`;
  el.miniAccounts.innerHTML=PLATFORMS.map(p=>`<div class="mini-account"><i class="${browserSessions[p.id]?'ready':''}"></i><span class="network-badge" style="background:${p.color}">${p.badge}</span><strong>${p.name}</strong></div>`).join('');
  el.recentPostsBody.innerHTML=[...state.posts].sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).slice(0,5).map(postRow).join('');bindDynamicPostClicks();
}
function postRow(p){return`<tr data-edit-post="${p.id}"><td class="post-cell"><strong>${escapeHtml(postTitle(p))}</strong><small>${escapeHtml(normaliseHashtags(p.hashtags)||'No hashtags')}</small></td><td>${platformBadges(p.platforms)}</td><td>${campaignTag(p.campaignId)}</td><td>${escapeHtml(formatDateTime(p.scheduledAt,true))}</td><td>${statusPill(p.status)}</td><td><button class="row-menu" aria-label="Edit">•••</button></td></tr>`}
function bindDynamicPostClicks(){$$('[data-edit-post]').forEach(node=>{if(!node.dataset.bound){node.dataset.bound='1';node.addEventListener('click',event=>{event.stopPropagation();openPostModal(node.dataset.editPost)})}});$$('[data-new-post]').forEach(button=>{if(!button.dataset.bound){button.dataset.bound='1';button.addEventListener('click',()=>openPostModal())}})}

function renderCalendar(){
  el.calendarMonthTitle.textContent=new Intl.DateTimeFormat('en-GB',{month:'long',year:'numeric'}).format(calendarCursor);const year=calendarCursor.getFullYear(),month=calendarCursor.getMonth(),first=new Date(year,month,1),offset=(first.getDay()+6)%7,start=new Date(year,month,1-offset);let html='';
  for(let i=0;i<42;i++){const day=new Date(start);day.setDate(start.getDate()+i);const key=toLocalDate(day),posts=sortedPosts().filter(p=>p.scheduledAt&&toLocalDate(new Date(p.scheduledAt))===key),other=day.getMonth()!==month,today=key===toLocalDate(new Date());html+=`<div class="calendar-day ${other?'other-month':''} ${today?'today':''}" data-calendar-day="${key}"><span class="day-number">${day.getDate()}</span><div class="day-posts">${posts.slice(0,3).map(p=>`<div class="calendar-post ${p.status}" data-edit-post="${p.id}" title="${escapeHtml(postTitle(p))}">${escapeHtml(postTitle(p))}</div>`).join('')}${posts.length>3?`<span class="more-posts">+${posts.length-3} more</span>`:''}</div></div>`}
  el.calendarGrid.innerHTML=html;$$('[data-calendar-day]').forEach(day=>day.addEventListener('click',event=>{if(event.target.closest('[data-edit-post]'))return;openPostModal(null,day.dataset.calendarDay)}));bindDynamicPostClicks();
}
function renderPostsLibrary(){const q=el.postSearch.value.trim().toLowerCase(),status=el.statusFilter.value,channel=el.platformFilter.value;const posts=[...state.posts].sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).filter(p=>(status==='all'||p.status===status)&&(channel==='all'||p.platforms.includes(channel))&&(!q||[p.caption,p.hashtags,p.notes,campaign(p.campaignId)?.name].join(' ').toLowerCase().includes(q)));el.allPostsBody.innerHTML=posts.map(postRow).join('');el.postsEmpty.hidden=posts.length>0;bindDynamicPostClicks()}
function renderMediaLibrary(){
  const q=(el.mediaSearch?.value||'').trim().toLowerCase(),type=el.mediaTypeFilter?.value||'all',items=[...state.media].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).filter(item=>(type==='all'||item.type===type)&&(!q||item.name.toLowerCase().includes(q)));
  const total=state.media.reduce((sum,item)=>sum+item.size,0),original=state.media.reduce((sum,item)=>sum+item.originalSize,0);el.mediaCountStat.textContent=state.media.length;el.mediaStorageStat.textContent=formatBytes(total);el.mediaSavedStat.textContent=formatBytes(Math.max(0,original-total));el.mediaEmpty.hidden=items.length>0;
  el.mediaGrid.innerHTML=items.map(item=>`<article class="media-card" data-media-card="${item.id}"><div class="media-preview" data-media-preview="${item.id}"><span><svg viewBox="0 0 24 24">${item.type==='video'?'<path d="M4 6h16v12H4Z"/><path d="m10 9 5 3-5 3Z"/>':'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="m4 17 5-5 3.5 3.5 2-2L20 19"/>'}</svg></span><i>${item.type.toUpperCase()}</i></div><div class="media-card-copy"><strong title="${escapeHtml(item.name)}">${escapeHtml(item.name)}</strong><small>${formatBytes(item.size)}${item.originalSize>item.size?` · saved ${formatBytes(item.originalSize-item.size)}`:''}</small></div><div class="media-card-actions"><button type="button" data-use-media="${item.id}">Use in post</button><button type="button" data-view-media="${item.id}">View</button><button class="delete-media" type="button" data-delete-media="${item.id}" aria-label="Delete">×</button></div></article>`).join('');
  hydrateMediaPreviews(items);$$('[data-use-media]').forEach(b=>b.addEventListener('click',()=>{openPostModal();selectedMediaId=b.dataset.useMedia;renderMediaOptions();updateSelectedMediaInfo()}));$$('[data-view-media]').forEach(b=>b.addEventListener('click',async()=>{const item=state.media.find(x=>x.id===b.dataset.viewMedia),url=await getMediaSignedUrl(item);if(url)window.open(url,'_blank','noopener')}));$$('[data-delete-media]').forEach(b=>b.addEventListener('click',()=>deleteMediaAsset(b.dataset.deleteMedia)));
}
async function getMediaSignedUrl(item){if(!item)return'';if(mediaSignedUrls.has(item.id))return mediaSignedUrls.get(item.id);const{data,error}=await db.storage.from('tech-social-media').createSignedUrl(item.path,3600);if(error){toast(`Could not open media: ${error.message}`,true);return''}mediaSignedUrls.set(item.id,data.signedUrl);return data.signedUrl}
async function hydrateMediaPreviews(items){for(const item of items.filter(x=>x.type==='image')){const holder=document.querySelector(`[data-media-preview="${item.id}"]`);if(!holder)continue;const url=await getMediaSignedUrl(item);if(url&&holder.isConnected)holder.innerHTML=`<img src="${url}" alt="${escapeHtml(item.name)}" loading="lazy" /><i>IMAGE</i>`}}
function renderMediaOptions(){const current=selectedMediaId;el.postMediaSelect.innerHTML='<option value="">No media selected</option>'+state.media.map(item=>`<option value="${item.id}">${escapeHtml(item.name)} · ${formatBytes(item.size)}</option>`).join('');el.postMediaSelect.value=state.media.some(item=>item.id===current)?current:'';selectedMediaId=el.postMediaSelect.value}
function updateSelectedMediaInfo(){const item=state.media.find(x=>x.id===selectedMediaId);el.selectedMediaInfo.innerHTML=item?`<svg viewBox="0 0 24 24">${item.type==='video'?'<path d="M4 6h16v12H4Z"/><path d="m10 9 5 3-5 3Z"/>':'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="m4 17 5-5 3.5 3.5 2-2L20 19"/>'}</svg><div><strong>${escapeHtml(item.name)}</strong><small>${item.type} · ${formatBytes(item.size)}</small></div>`:'<svg viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="m4 17 5-5 3.5 3.5 2-2L20 19"/></svg><div><strong>No media selected</strong><small>Choose an optimised library file</small></div>'}
function openMediaUploadModal(){queuedMediaFiles=[];el.mediaUploadInput.value='';el.mediaUploadQueue.innerHTML='';el.mediaUploadError.textContent='';el.startMediaUploadButton.disabled=true;openModal(el.mediaUploadModal)}
function queueMediaFiles(files){const accepted=[];for(const file of files){const image=['image/jpeg','image/png','image/webp'].includes(file.type),video=['video/mp4','video/webm','video/quicktime'].includes(file.type);if(!image&&!video)continue;if(video&&file.size>52428800){el.mediaUploadError.textContent=`${file.name} is larger than the 50 MB video limit.`;continue}if(image&&file.size>26214400){el.mediaUploadError.textContent=`${file.name} is too large to optimise in the browser.`;continue}accepted.push(file)}queuedMediaFiles=accepted;el.startMediaUploadButton.disabled=!accepted.length;el.mediaUploadQueue.innerHTML=accepted.map((file,index)=>`<div class="upload-queue-item" data-upload-row="${index}"><span>${file.type.startsWith('video/')?'VIDEO':'IMAGE'}</span><div><strong>${escapeHtml(file.name)}</strong><small>${formatBytes(file.size)} · waiting</small></div><i></i></div>`).join('')}
async function optimiseImage(file){const bitmap=await createImageBitmap(file),scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),width=Math.max(1,Math.round(bitmap.width*scale)),height=Math.max(1,Math.round(bitmap.height*scale)),canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const context=canvas.getContext('2d',{alpha:false});context.drawImage(bitmap,0,0,width,height);bitmap.close?.();const blob=await new Promise((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('Image compression failed.')),'image/webp',.78));return{blob,width,height,mime:'image/webp',name:file.name.replace(/\.[^.]+$/, '')+'.webp'}}
async function readVideoMetadata(file){return new Promise(resolve=>{const video=document.createElement('video'),url=URL.createObjectURL(file),done=()=>{const data={width:video.videoWidth||null,height:video.videoHeight||null,duration:Number.isFinite(video.duration)?video.duration:null};URL.revokeObjectURL(url);resolve(data)};video.preload='metadata';video.onloadedmetadata=done;video.onerror=()=>{URL.revokeObjectURL(url);resolve({width:null,height:null,duration:null})};video.src=url})}
async function hashBlob(blob){const digest=await crypto.subtle.digest('SHA-256',await blob.arrayBuffer());return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
async function uploadQueuedMedia(){if(!queuedMediaFiles.length)return;el.startMediaUploadButton.disabled=true;el.mediaUploadError.textContent='';let uploaded=0,lastId='';for(let index=0;index<queuedMediaFiles.length;index++){const file=queuedMediaFiles[index],row=el.mediaUploadQueue.querySelector(`[data-upload-row="${index}"]`),status=row?.querySelector('small'),indicator=row?.querySelector('i');try{if(status)status.textContent=`${formatBytes(file.size)} · optimising…`;let blob=file,name=file.name,mime=file.type,width=null,height=null,duration=null;if(file.type.startsWith('image/')){const optimised=await optimiseImage(file);blob=optimised.blob;name=optimised.name;mime=optimised.mime;width=optimised.width;height=optimised.height}else{const meta=await readVideoMetadata(file);width=meta.width;height=meta.height;duration=meta.duration}const hash=await hashBlob(blob),duplicate=state.media.find(item=>item.hash===hash);if(duplicate){lastId=duplicate.id;if(status)status.textContent=`Duplicate found · reused ${duplicate.name}`;indicator?.classList.add('done');continue}const extension=mime==='image/webp'?'webp':mime==='video/webm'?'webm':mime==='video/quicktime'?'mov':'mp4',path=`media/${hash}.${extension}`;if(status)status.textContent=`${formatBytes(blob.size)} · uploading…`;const uploadResult=await db.storage.from('tech-social-media').upload(path,blob,{contentType:mime,cacheControl:'31536000',upsert:false});if(uploadResult.error)throw uploadResult.error;const record={storage_path:path,content_hash:hash,original_name:name,mime_type:mime,media_type:mime.startsWith('image/')?'image':'video',size_bytes:blob.size,original_size_bytes:file.size,width,height,duration_seconds:duration,uploaded_by:currentUser.id};const insertResult=await db.from('media_assets').insert(record).select().single();if(insertResult.error){await db.storage.from('tech-social-media').remove([path]);throw insertResult.error}const item=mediaFromDb(insertResult.data);state.media.push(item);lastId=item.id;uploaded++;if(status)status.textContent=`${formatBytes(item.size)} · uploaded`;indicator?.classList.add('done')}catch(error){if(status)status.textContent=`Failed · ${error.message}`;indicator?.classList.add('failed')}}renderMediaLibrary();if(lastId){selectedMediaId=lastId;renderMediaOptions();updateSelectedMediaInfo()}el.startMediaUploadButton.disabled=false;toast(`${uploaded} new media ${uploaded===1?'file':'files'} uploaded and optimised.`)}
async function deleteMediaAsset(id){const item=state.media.find(x=>x.id===id);if(!item||!confirm(`Delete ${item.name} from the shared media library?`))return;const storageResult=await db.storage.from('tech-social-media').remove([item.path]);if(storageResult.error){toast(`Could not delete file: ${storageResult.error.message}`,true);return}const dbResult=await db.from('media_assets').delete().eq('id',id);if(dbResult.error){toast(`File removed but record cleanup failed: ${dbResult.error.message}`,true);return}state.media=state.media.filter(x=>x.id!==id);state.posts=state.posts.map(post=>post.mediaId===id?{...post,mediaId:'',mediaName:''}:post);mediaSignedUrls.delete(id);renderAll();toast('Media deleted and removed from linked posts.')}

function renderCampaigns(){el.campaignGrid.innerHTML=state.campaigns.map(c=>{const posts=state.posts.filter(p=>p.campaignId===c.id),next=posts.filter(p=>p.status!=='published'&&p.scheduledAt).sort((a,b)=>new Date(a.scheduledAt)-new Date(b.scheduledAt))[0];return`<article class="campaign-card" style="--campaign-color:${c.colour}" data-edit-campaign="${c.id}"><span><svg viewBox="0 0 24 24"><path d="M4 18V6l11-3v18L4 18Z"/><path d="m15 8 5 2v8l-5 3"/></svg></span><h3>${escapeHtml(c.name)}</h3><p>${escapeHtml(c.description||'No campaign description yet.')}</p><div class="campaign-meta"><span><strong>${posts.length}</strong> posts</span><span>${next?`Next: ${formatDayMonth(next.scheduledAt)}`:'No upcoming posts'}</span></div></article>`}).join('')+`<button class="new-campaign-card" id="campaignAddCard" type="button"><span>+</span><strong>Create campaign</strong></button>`;$$('[data-edit-campaign]').forEach(card=>card.addEventListener('click',()=>openCampaignModal(card.dataset.editCampaign)));$('#campaignAddCard').addEventListener('click',()=>openCampaignModal())}
function renderQueue(){const posts=queuePosts();el.queueEmpty.hidden=posts.length>0;el.queueList.innerHTML=posts.map(p=>{const d=new Date(p.scheduledAt),due=isDue(p);return`<article class="queue-card"><div class="queue-date"><small>${d.toLocaleDateString('en-GB',{month:'short'}).toUpperCase()}</small><strong>${d.getDate()}</strong><span>${d.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}</span></div><div class="queue-copy"><strong>${escapeHtml(postTitle(p))}</strong><p>${escapeHtml(p.notes||normaliseHashtags(p.hashtags)||'No internal notes')}</p><div class="queue-meta">${platformBadges(p.platforms)}${campaignTag(p.campaignId)}${due?'<span class="status-pill ready">DUE NOW</span>':statusPill(p.status)}</div></div><div class="queue-actions"><button class="button button-outline" data-edit-post="${p.id}">Edit</button><button class="button button-primary" data-publish-post="${p.id}">${due?'Publish now':'Open publisher'}</button></div></article>`}).join('');bindDynamicPostClicks();$$('[data-publish-post]').forEach(b=>b.addEventListener('click',()=>openPublishModal(b.dataset.publishPost)))}
function renderAccounts(){el.accountsGrid.innerHTML=PLATFORMS.map(p=>{const ready=Boolean(browserSessions[p.id]),destination=ready?p.sessionUrl:p.login;return`<article class="account-card"><div class="account-card-top"><span class="network-badge" style="background:${p.color}">${p.badge}</span><div><strong>${p.name}</strong><small>${ready?'This browser is ready to reuse the saved network session':'Sign in once on this browser, then mark ready'}</small></div><i class="account-state ${ready?'ready':''}"></i></div><p>${ready?'Open the account directly. If the network cookie is still valid, you will not be asked to sign in again.':`${p.description}. Sign-in happens only on the official ${p.name} website.`}</p><div class="account-card-actions"><a href="${destination}" target="_blank" rel="noopener noreferrer">${ready?'Open account':'Sign in once'}</a><button class="${ready?'ready':''}" data-toggle-account="${p.id}">${ready?'Session ready ✓':'Mark ready'}</button></div></article>`}).join('');$$('[data-toggle-account]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.toggleAccount,next=!browserSessions[id];browserSessions[id]=next;saveBrowserSessions();renderAll();toast(`${platform(id).name} ${next?'marked ready on this browser — its saved network session will be reused':'browser session reminder removed'}.`)}))}

function renderPlatformPicker(){el.platformPicker.innerHTML=PLATFORMS.map(p=>`<label class="platform-option"><input type="checkbox" value="${p.id}" /><span class="network-badge" style="background:${p.color}">${p.badge}</span><strong>${p.name}</strong><i>✓</i></label>`).join('');el.platformPicker.querySelectorAll('input').forEach(input=>input.addEventListener('change',()=>{selectedPlatforms=el.platformPicker.querySelectorAll('input:checked').length?[...el.platformPicker.querySelectorAll('input:checked')].map(i=>i.value):[]}))}
function openPostModal(id=null,date=null){
  const post=id?state.posts.find(p=>p.id===id):null;el.postForm.reset();el.postId.value=post?.id||'';el.postModalTitle.textContent=post?'Edit social post':'Create social post';el.postCaption.value=post?.caption||'';el.postLink.value=DEFAULT_POST_URL;el.postHashtags.value=post?.hashtags||'';el.postNotes.value=post?.notes||'';selectedPlatforms=post?.platforms?[...post.platforms]:['instagram','facebook'];el.platformPicker.querySelectorAll('input').forEach(input=>input.checked=selectedPlatforms.includes(input.value));
  const dt=post?.scheduledAt?new Date(post.scheduledAt):new Date();if(!post){dt.setHours(dt.getHours()+1,0,0,0)}el.postDate.value=date||toLocalDate(dt);el.postTime.value=post?dt.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false}):dt.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false});renderCampaignOptions(post?.campaignId);el.postStatus.value=post?.status||'draft';selectedMediaId=post?.mediaId||'';renderMediaOptions();updateSelectedMediaInfo();el.deletePostButton.hidden=!post;el.postFormError.textContent='';updateCaptionCount();openModal(el.postModal);setTimeout(()=>el.postCaption.focus(),60)
}
function updateCaptionCount(){const n=el.postCaption.value.length;el.postCaptionCount.textContent=`${n.toLocaleString()} ${n===1?'character':'characters'}`}
function renderCampaignOptions(selected=''){el.postCampaign.innerHTML='<option value="">No campaign</option>'+state.campaigns.map(c=>`<option value="${c.id}" ${c.id===selected?'selected':''}>${escapeHtml(c.name)}</option>`).join('')}
async function savePostFromForm(event){event.preventDefault();const caption=el.postCaption.value.trim();if(!caption){el.postFormError.textContent='Add a caption before saving.';return}if(!selectedPlatforms.length){el.postFormError.textContent='Select at least one social channel.';return}if(!el.postDate.value||!el.postTime.value){el.postFormError.textContent='Choose a publishing date and time.';return}if(el.postLink.value.trim()){try{new URL(el.postLink.value.trim())}catch{el.postFormError.textContent='Enter a complete link beginning with http:// or https://';return}}
  const existing=state.posts.find(p=>p.id===el.postId.value),media=state.media.find(item=>item.id===selectedMediaId),now=new Date().toISOString(),record={id:existing?.id||uid('post'),caption,link:DEFAULT_POST_URL,hashtags:el.postHashtags.value.trim(),notes:el.postNotes.value.trim(),platforms:[...selectedPlatforms],scheduledAt:new Date(`${el.postDate.value}T${el.postTime.value}:00`).toISOString(),status:el.postStatus.value,campaignId:el.postCampaign.value,mediaId:media?.id||'',mediaName:media?.name||'',createdAt:existing?.createdAt||now,updatedAt:now},submit=el.postForm.querySelector('[type="submit"]');submit.disabled=true;submit.textContent='Saving…';const{error}=await db.from('posts').upsert(postToDb(record));submit.disabled=false;submit.textContent='Save post';if(error){el.postFormError.textContent=`Could not save: ${error.message}`;return}if(existing)state.posts=state.posts.map(p=>p.id===existing.id?record:p);else state.posts.push(record);closeModal(el.postModal);renderAll();toast(existing?'Post updated for the team.':'Post added to the shared CRM.')}
async function deleteCurrentPost(){const id=el.postId.value;if(!id||!confirm('Delete this social post permanently?'))return;el.deletePostButton.disabled=true;const{error}=await db.from('posts').delete().eq('id',id);el.deletePostButton.disabled=false;if(error){toast(`Could not delete post: ${error.message}`,true);return}state.posts=state.posts.filter(p=>p.id!==id);closeModal(el.postModal);renderAll();toast('Post deleted.')}

function renderColourPicker(){el.colourPicker.innerHTML=COLOURS.map((c,i)=>`<button class="colour-button ${i===0?'active':''}" style="--colour:${c}" data-colour="${c}" type="button" aria-label="Choose colour"></button>`).join('');$$('[data-colour]').forEach(b=>b.addEventListener('click',()=>{selectedCampaignColour=b.dataset.colour;$$('[data-colour]').forEach(x=>x.classList.toggle('active',x===b))}))}
function openCampaignModal(id=null){const c=id?campaign(id):null;el.campaignForm.reset();el.campaignId.value=c?.id||'';el.campaignName.value=c?.name||'';el.campaignDescription.value=c?.description||'';selectedCampaignColour=c?.colour||COLOURS[0];$$('[data-colour]').forEach(b=>b.classList.toggle('active',b.dataset.colour===selectedCampaignColour));el.deleteCampaignButton.hidden=!c;openModal(el.campaignModal);setTimeout(()=>el.campaignName.focus(),60)}
async function saveCampaignFromForm(event){event.preventDefault();const name=el.campaignName.value.trim();if(!name)return;const existing=campaign(el.campaignId.value),now=new Date().toISOString(),record={id:existing?.id||uid('camp'),name,description:el.campaignDescription.value.trim(),colour:selectedCampaignColour,createdAt:existing?.createdAt||now,updatedAt:now},submit=el.campaignForm.querySelector('[type="submit"]');submit.disabled=true;const{error}=await db.from('campaigns').upsert(campaignToDb(record));submit.disabled=false;if(error){toast(`Could not save campaign: ${error.message}`,true);return}if(existing)state.campaigns=state.campaigns.map(c=>c.id===existing.id?record:c);else state.campaigns.push(record);closeModal(el.campaignModal);renderAll();toast(existing?'Campaign updated for the team.':'Campaign created.')}
async function deleteCurrentCampaign(){const id=el.campaignId.value;if(!id||!confirm('Delete this campaign? Its posts will remain uncategorised.'))return;el.deleteCampaignButton.disabled=true;const{error}=await db.from('campaigns').delete().eq('id',id);el.deleteCampaignButton.disabled=false;if(error){toast(`Could not delete campaign: ${error.message}`,true);return}state.campaigns=state.campaigns.filter(c=>c.id!==id);state.posts=state.posts.map(p=>p.campaignId===id?{...p,campaignId:'',updatedAt:new Date().toISOString()}:p);closeModal(el.campaignModal);renderAll();toast('Campaign deleted.')}

function openPublishModal(id){const post=state.posts.find(p=>p.id===id);if(!post)return;publishingPostId=id;const media=state.media.find(item=>item.id===post.mediaId);el.publishMediaReference.hidden=!media;el.publishMediaName.textContent=media?.name||'';el.publishModalTitle.textContent=isDue(post)?'This post is ready':'Prepare publishing session';el.publishCaptionPreview.textContent=buildCaption(post)||'No caption';el.publishResults.innerHTML=post.platforms.map(pid=>{const p=platform(pid);return`<div class="publish-result"><span class="network-badge" style="background:${p.color}">${p.badge}</span><div><strong>${p.name}</strong><small>${browserSessions[pid]?'This browser is marked ready':'Sign in once on this browser before publishing'}</small></div><a href="${p.composer(post)}" target="_blank" rel="noopener noreferrer">Open</a></div>`}).join('');openModal(el.publishModal)}
async function openPublishingMedia(){const post=state.posts.find(p=>p.id===publishingPostId),media=state.media.find(item=>item.id===post?.mediaId);if(!media)return;const url=await getMediaSignedUrl(media);if(url)window.open(url,'_blank','noopener')}
async function copyText(text){try{await navigator.clipboard.writeText(text);return true}catch{const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.select();let ok=false;try{ok=document.execCommand('copy')}catch{}t.remove();return ok}}
async function copyPublishingCaption(){const post=state.posts.find(p=>p.id===publishingPostId);if(!post)return;const ok=await copyText(buildCaption(post));toast(ok?'Caption copied.':'Could not copy automatically.',!ok)}
async function openPublishingPages(){const post=state.posts.find(p=>p.id===publishingPostId);if(!post)return;const copyPromise=copyText(buildCaption(post));let opened=0;post.platforms.forEach(pid=>{const p=platform(pid);try{const tab=window.open('about:blank','_blank');if(tab){tab.opener=null;tab.location.href=p.composer(post);opened++}}catch{}});const copied=await copyPromise;toast(`${opened} of ${post.platforms.length} pages opened${copied?' and caption copied':''}.`,opened<post.platforms.length)}
async function markPublishingPostComplete(){const post=state.posts.find(p=>p.id===publishingPostId);if(!post)return;const updatedAt=new Date().toISOString();el.markPublishedButton.disabled=true;const{error}=await db.from('posts').update({status:'published',updated_at:updatedAt,updated_by:currentUser.id}).eq('id',post.id);el.markPublishedButton.disabled=false;if(error){toast(`Could not update post: ${error.message}`,true);return}post.status='published';post.updatedAt=updatedAt;closeModal(el.publishModal);renderAll();toast('Post marked as published for the team.')}

function renderRequests(){const open=state.requests.filter(r=>r.status==='open').length,progress=state.requests.filter(r=>r.status==='in_progress').length,completed=state.requests.filter(r=>r.status==='completed').length;el.openRequestsStat.textContent=open;el.progressRequestsStat.textContent=progress;el.completedRequestsStat.textContent=completed;const status=el.requestStatusFilter.value,type=el.requestTypeFilter.value,items=[...state.requests].sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).filter(r=>(status==='all'||r.status===status)&&(type==='all'||r.type===type));el.requestsEmpty.hidden=items.length>0;const colours={low:'#8e949a',normal:'#356fd5',high:'#d99a12',urgent:'#ef111b'};el.requestList.innerHTML=items.map(r=>`<article class="request-card" data-edit-request="${r.id}"><i class="priority-bar" style="--priority:${colours[r.priority]}"></i><div class="request-copy"><strong>${escapeHtml(r.title)}</strong><p>${escapeHtml(r.details||'No additional details.')}</p><small>Requested by ${escapeHtml(r.requestedByName)} · ${formatDateTime(r.createdAt,true)}${r.assignedTo?` · Assigned to ${escapeHtml(r.assignedTo)}`:''}</small></div><div class="request-side"><span class="request-type-badge">${r.type==='content_approval'?'Content approval':'Information'}</span><select class="request-status-select" data-request-status="${r.id}"><option value="open" ${r.status==='open'?'selected':''}>Open</option><option value="in_progress" ${r.status==='in_progress'?'selected':''}>In progress</option><option value="completed" ${r.status==='completed'?'selected':''}>Completed</option></select></div></article>`).join('');$$('[data-edit-request]').forEach(card=>card.addEventListener('click',event=>{if(event.target.closest('[data-request-status]'))return;openRequestModal(card.dataset.editRequest)}));$$('[data-request-status]').forEach(select=>select.addEventListener('change',()=>updateRequestStatus(select.dataset.requestStatus,select.value)))}
function openRequestModal(id=''){const item=state.requests.find(r=>r.id===id);el.requestForm.reset();el.requestId.value=item?.id||'';el.requestType.value=item?.type||'information';el.requestPriority.value=item?.priority||'normal';el.requestTitle.value=item?.title||'';el.requestDetails.value=item?.details||'';el.requestAssignee.value=item?.assignedTo||'';el.requestRelatedPost.innerHTML='<option value="">No related post</option>'+state.posts.map(post=>`<option value="${post.id}">${escapeHtml(postTitle(post))}</option>`).join('');el.requestRelatedPost.value=item?.relatedPostId||'';el.deleteRequestButton.hidden=!item;openModal(el.requestModal);setTimeout(()=>el.requestTitle.focus(),50)}
async function saveRequest(event){event.preventDefault();const existing=state.requests.find(r=>r.id===el.requestId.value),now=new Date().toISOString(),record={id:existing?.id,title:el.requestTitle.value.trim(),details:el.requestDetails.value.trim(),request_type:el.requestType.value,priority:el.requestPriority.value,status:existing?.status||'open',requested_by:existing?.requestedBy||currentUser.id,requested_by_email:existing?.requestedByEmail||currentUser.email,requested_by_name:existing?.requestedByName||currentDisplayName,assigned_to_email:el.requestAssignee.value.trim().toLowerCase()||null,related_post_id:el.requestRelatedPost.value||null,related_campaign_id:null,created_at:existing?.createdAt||now,updated_at:now};if(!record.title)return;const query=existing?db.from('team_requests').update(record).eq('id',existing.id):db.from('team_requests').insert(record).select().single(),result=await query;if(result.error){toast(`Could not save request: ${result.error.message}`,true);return}if(existing){const mapped=requestFromDb({...record,id:existing.id});state.requests=state.requests.map(r=>r.id===existing.id?mapped:r)}else state.requests.push(requestFromDb(result.data));closeModal(el.requestModal);renderAll();toast(existing?'Request updated.':'Request shared with the team.')}
async function updateRequestStatus(id,status){const now=new Date().toISOString(),result=await db.from('team_requests').update({status,updated_at:now}).eq('id',id);if(result.error){toast(`Could not update request: ${result.error.message}`,true);return}const item=state.requests.find(r=>r.id===id);if(item){item.status=status;item.updatedAt=now}renderRequests();updateCounts()}
async function deleteCurrentRequest(){const id=el.requestId.value;if(!id||!confirm('Delete this team request?'))return;const result=await db.from('team_requests').delete().eq('id',id);if(result.error){toast(result.error.message,true);return}state.requests=state.requests.filter(r=>r.id!==id);closeModal(el.requestModal);renderAll();toast('Request deleted.')}
function inboxPlatform(id){return platform(id)||{id:'other',name:'Other',badge:'•',color:'#71747b'}}
function renderInbox(){const q=(el.threadSearch.value||'').trim().toLowerCase(),threads=[...state.threads].sort((a,b)=>new Date(b.lastMessageAt)-new Date(a.lastMessageAt)).filter(t=>!q||[t.contactName,t.contactHandle,t.subject,t.platform].join(' ').toLowerCase().includes(q));el.threadEmpty.hidden=threads.length>0;el.threadList.innerHTML=threads.map(t=>{const p=inboxPlatform(t.platform),latest=[...state.messages].filter(m=>m.threadId===t.id).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))[0];return`<article class="thread-item ${t.id===activeThreadId?'active':''}" data-thread-id="${t.id}"><span class="network-badge" style="background:${p.color}">${p.badge}</span><div><strong>${escapeHtml(t.contactName)}</strong><small>${escapeHtml(t.contactHandle||p.name)} · ${t.status}</small><p>${escapeHtml(latest?.body||t.subject||'No messages')}</p></div><time>${formatDateTime(t.lastMessageAt,true)}</time></article>`}).join('');$$('[data-thread-id]').forEach(item=>item.addEventListener('click',()=>{activeThreadId=item.dataset.threadId;renderInbox()}));const thread=state.threads.find(t=>t.id===activeThreadId);el.conversationPlaceholder.hidden=Boolean(thread);el.activeConversation.hidden=!thread;if(!thread)return;const p=inboxPlatform(thread.platform);el.conversationPlatformBadge.textContent=p.badge;el.conversationPlatformBadge.style.background=p.color;el.conversationContact.textContent=`${thread.contactName}${thread.contactHandle?` (${thread.contactHandle})`:''}`;el.conversationSubject.textContent=thread.subject||`${p.name} conversation`;el.conversationStatus.value=thread.status;const messages=state.messages.filter(m=>m.threadId===thread.id).sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt));el.messageList.innerHTML=messages.map(m=>`<div class="message-row ${m.type}"><div class="message-bubble">${escapeHtml(m.body)}</div><div class="message-meta"><span>${escapeHtml(m.senderName)}</span><time>${formatDateTime(m.createdAt,true)}</time><span>${m.type==='internal'?'Team note':m.type==='inbound'?'Customer message':'Reply record'}</span></div></div>`).join('');el.messageList.scrollTop=el.messageList.scrollHeight}
function openThreadModal(){el.threadForm.reset();openModal(el.threadModal);setTimeout(()=>el.threadContactName.focus(),50)}
async function createThread(event){event.preventDefault();const now=new Date().toISOString(),threadRecord={platform:el.threadPlatform.value,contact_name:el.threadContactName.value.trim(),contact_handle:el.threadContactHandle.value.trim(),subject:el.threadSubject.value.trim(),status:'open',created_by:currentUser.id,created_at:now,updated_at:now,last_message_at:now};if(!threadRecord.contact_name)return;let result=await db.from('social_threads').insert(threadRecord).select().single();if(result.error){toast(`Could not create conversation: ${result.error.message}`,true);return}const thread=threadFromDb(result.data),messageRecord={thread_id:thread.id,message_type:'inbound',body:el.threadFirstMessage.value.trim(),sender_name:thread.contactName,sender_user_id:null,created_at:now};result=await db.from('social_messages').insert(messageRecord).select().single();if(result.error){await db.from('social_threads').delete().eq('id',thread.id);toast(`Could not save message: ${result.error.message}`,true);return}state.threads.push(thread);state.messages.push(messageFromDb(result.data));activeThreadId=thread.id;closeModal(el.threadModal);renderAll();showView('inbox');toast('Conversation added to the shared inbox.')}
async function addThreadMessage(event){event.preventDefault();const thread=state.threads.find(t=>t.id===activeThreadId),body=el.messageBody.value.trim();if(!thread||!body)return;const now=new Date().toISOString(),type=el.messageType.value,record={thread_id:thread.id,message_type:type,body,sender_name:type==='inbound'?thread.contactName:currentDisplayName,sender_user_id:type==='inbound'?null:currentUser.id,created_at:now},result=await db.from('social_messages').insert(record).select().single();if(result.error){toast(`Could not add message: ${result.error.message}`,true);return}await db.from('social_threads').update({last_message_at:now,updated_at:now}).eq('id',thread.id);state.messages.push(messageFromDb(result.data));thread.lastMessageAt=now;thread.updatedAt=now;el.messageBody.value='';renderInbox();updateCounts()}
async function updateThreadStatus(){const thread=state.threads.find(t=>t.id===activeThreadId);if(!thread)return;const status=el.conversationStatus.value,now=new Date().toISOString(),result=await db.from('social_threads').update({status,updated_at:now}).eq('id',thread.id);if(result.error){toast(result.error.message,true);return}thread.status=status;thread.updatedAt=now;renderInbox();updateCounts()}
function showSettingsTab(tab){$$('[data-settings-tab]').forEach(button=>button.classList.toggle('active',button.dataset.settingsTab===tab));$$('[data-settings-pane]').forEach(pane=>{pane.hidden=pane.dataset.settingsPane!==tab;pane.classList.toggle('active',pane.dataset.settingsPane===tab)})}
function renderSettings(){el.profileDisplayName.value=currentDisplayName;el.profileEmail.value=currentUser?.email||'';el.profileAvatar.textContent=(currentDisplayName||'TL').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();el.versionHistory.innerHTML=VERSION_HISTORY.map((release,index)=>`<article class="version-card ${index===0?'current':''}"><header><h4>Version ${release.version}${index===0?' · Current':''}</h4><time>${release.date}</time></header><p>${release.summary}</p><ul>${release.changes.map(change=>`<li>${escapeHtml(change)}</li>`).join('')}</ul></article>`).join('')}
async function saveProfile(event){event.preventDefault();const name=el.profileDisplayName.value.trim();if(!name)return;const result=await db.from('allowed_users').update({display_name:name}).eq('email',currentUser.email.toLowerCase());if(result.error){el.profileMessage.textContent=result.error.message;el.profileMessage.classList.add('error');return}currentDisplayName=name;const initials=name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();el.userDisplayName.textContent=name;el.userInitials.textContent=initials;el.profileAvatar.textContent=initials;setDateGreeting();el.profileMessage.textContent='Profile updated for your account.';el.profileMessage.classList.remove('error')}
async function changePassword(event){event.preventDefault();if(el.newPassword.value!==el.confirmPassword.value){el.passwordMessage.textContent='The passwords do not match.';el.passwordMessage.classList.add('error');return}const result=await db.auth.updateUser({password:el.newPassword.value});if(result.error){el.passwordMessage.textContent=result.error.message;el.passwordMessage.classList.add('error');return}el.passwordForm.reset();el.passwordMessage.textContent='Password changed successfully.';el.passwordMessage.classList.remove('error')}
function compareVersions(a,b){const pa=String(a).split('.').map(Number),pb=String(b).split('.').map(Number);for(let i=0;i<Math.max(pa.length,pb.length);i++){if((pa[i]||0)!==(pb[i]||0))return(pa[i]||0)-(pb[i]||0)}return 0}
async function checkForUpdates(){el.checkVersionButton.disabled=true;el.versionStatus.textContent='Checking for updates…';try{const response=await fetch(`version.json?time=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error('Version information unavailable.');const info=await response.json();el.versionStatus.textContent=compareVersions(info.version,APP_VERSION)>0?`Version ${info.version} is available. Refresh after the repository update is deployed.`:`You are up to date on version ${APP_VERSION}.`}catch(error){el.versionStatus.textContent=error.message}finally{el.checkVersionButton.disabled=false}}

function exportData(){const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`tech-social-crm-backup-${toLocalDate(new Date())}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500);toast('CRM backup downloaded.')}
function importData(){const file=el.importInput.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=async()=>{try{const data=JSON.parse(reader.result);if(!Array.isArray(data.posts)||!Array.isArray(data.campaigns))throw new Error('Invalid backup format.');if(!confirm('Replace the shared CRM data with this backup for every team member?'))return;const campaigns=data.campaigns.map(c=>({...c,updatedAt:c.updatedAt||new Date().toISOString()})),posts=data.posts.map(p=>({...p,createdAt:p.createdAt||new Date().toISOString(),updatedAt:p.updatedAt||new Date().toISOString()})),accounts={...Object.fromEntries(PLATFORMS.map(p=>[p.id,false])),...(data.accounts||{})};let result=await db.from('posts').delete().not('id','is',null);if(result.error)throw result.error;result=await db.from('campaigns').delete().not('id','is',null);if(result.error)throw result.error;if(campaigns.length){result=await db.from('campaigns').upsert(campaigns.map(campaignToDb));if(result.error)throw result.error}if(posts.length){result=await db.from('posts').upsert(posts.map(postToDb));if(result.error)throw result.error}result=await db.from('social_accounts').upsert(PLATFORMS.map(p=>({platform:p.id,ready:Boolean(accounts[p.id]),updated_at:new Date().toISOString(),updated_by:currentUser.id})));if(result.error)throw result.error;state={posts,campaigns,media:state.media,requests:state.requests,threads:state.threads,messages:state.messages,accounts};renderAll();toast('Shared CRM backup imported. Media files already in the library were preserved.')}catch(error){toast(error.message||'That file is not a valid Tech Social CRM backup.',true)}finally{el.importInput.value=''}};reader.readAsText(file)}
function openModal(modal){modal.hidden=false;document.body.style.overflow='hidden'}function closeModal(modal){modal.hidden=true;if(!$$('.modal-backdrop:not([hidden])').length)document.body.style.overflow=''}
function toast(message,warning=false){const n=document.createElement('div');n.className=`toast${warning?' warning':''}`;n.textContent=message;el.toastRegion.appendChild(n);setTimeout(()=>n.remove(),3500)}

initializeAuth();
